### PR TITLE
Fix aws_waf_sql_injection_match_set.sql_injection_match_set being modified on each apply 

### PR DESCRIPTION
**Pull request by tlopo**
## what
Terraform Plan always detect changes.

Root cause is in the AWS Provider:  https://github.com/hashicorp/terraform-provider-aws/issues/12538

This PR Fixes issue: https://github.com/binbashar/terraform-aws-waf-owasp/issues/14

## why
This is a workaround until AWS Provider is fixed.

## references
https://github.com/hashicorp/terraform-provider-aws/issues/12538
https://github.com/binbashar/terraform-aws-waf-owasp/issues/14

### CODE REVIEW

**Review by exequielrafaela — DISMISSED** [review]
@tlopo thanks for your collaboration here. Since there's still no aws provider fix (as you stated at https://github.com/binbashar/terraform-aws-waf-owasp/issues/14#issuecomment-764747944) I think this could be fine for a temporary fix.

@diego-ojeda-binbash What do you think about it?

**Review by exequielrafaela — APPROVED** [review]

**Comment by diego-ojeda-binbash** [comment]
@exequielrafaela @tlopo My only concern is this "ignore_changes = all" 😄 Do we really need to set it to "all"?

**Comment by exequielrafaela** [comment]
> @tlopo thanks for your collaboration here. Since there's still no aws provider fix (as you stated at [#14 (comment)](https://github.com/binbashar/terraform-aws-waf-owasp/issues/14#issuecomment-764747944)) I think this could be fine for a temporary fix.
> 
> @diego-ojeda-binbash What do you think about it?

@diego-ojeda-binbash  **_OJ_** I see your point here. @tlopo could you please try to reduce `lifecycle { ignore_changes = all }` for the  [`aws_waf_sql_injection_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_sql_injection_match_set) resource declaration to the most specific list of arguments possible?  

I've seen there are not that many arguments for this type of resource, but still, we think it would be worthy to give it a try declaring the specific resource arguments instead of using `all`.

- 📒 _simple example as reference_ -> https://github.com/binbashar/terraform-aws-ec2-basic-layout/blob/fac2c62ae719934afb9ea5837a93bbaa84a8c976/instances.tf#L83 (just ignoring the `aws_instance` resource `ami` argument).

**Review by exequielrafaela — CHANGES_REQUESTED** [review]
@tlopo Pleese consider the comment above -> https://github.com/binbashar/terraform-aws-waf-owasp/pull/29#issuecomment-765309291

**Comment by exequielrafaela** [comment]
@tlopo Please let us know anything else we can help you with in order to move forward with the change request detailed here.

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@tlopo please let us know if you have any updates for this PR based on our latest comment. If not we'll proceed to close it. Thanks in advance.

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@tlopo we'll close this issue because it has been inactive for more than a month. Please don't hesitate to let us know if you have any updates in the near future. 

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Pull request closed without merging**
